### ISSUE TITLE
Support MIDI out

### ISSUE THREAD

**Issue by TristanCacqueray** [mikesol/purescript-wags#36]
Currently, `FRP.Event.MIDI` only support receiving events. Here are some suggestions from @mikesol 

First bind the web midi API with: `sendMidi :: MidiAccess -> MIDIEvent -> Timestamp -> Effect Unit`

Then from an FRP standpoint, we may have something like (in pseudo-code):

```purescript
unsubscribe <- subscribe (interval 1000.0) \_ -> do
  sendMidi midiAccess (NoteOn 10) 10.0
  sendMidi midiAccess (NoteOn 20) 20.0
```

However, thinking it through as I'm writing, the cleaner way to do it would be to have it as part of the wags graph itself, meaning have something called midiOutput that works just like playBuf or sinOsc or any other node. This way, people could mix midi and audio freely.

**Comment by mikesol** [comment]
My proposal would be to have a single type called `MIDI` that takes an array of instructions. That's the simplest initial abstraction on top of which other more useful abstractions can be built.

**Comment by mikesol** [comment]
Implemented by @TristanCacqueray so closing.
